version: '3'

services:

    python:
        build:
            context: python_ctx
        command:
            tail -f /dev/null
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-catalog-provider:
        build:
            context: irods_ctx
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "test -f /tmp/flag || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 2s
